import java.util.Arrays;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million
 * find the sum of the even-evaluated sum
 */
public class EvenFibonnaci {
    public static void main(String[] args) {
        System.out.println(sumEvenFibonacci(1000000));
    }

    private static long sumEvenFibonacci(int n) {
        long[] dp = new long[n + 1];
        dp[0] = 1;
        dp[1] = 1;
        long evenFibs = 0;
        for (int i = 2; i <= n && dp[i-1] < 4000000; i++) {
            long fib = dp[i - 1] + dp[i - 2];
            if (fib % 2 == 0) evenFibs += fib;
            dp[i] = fib;
        }
        return evenFibs;
    }
}
